### ISSUE TITLE
RealValue test fails with internal error

### ISSUE THREAD

**Issue by wtatarski** [antmicro/verilator-old-archived#101]
RealValue test https://github.com/alainmarcel/uhdm-integration/tree/master/tests/RealValue
fails with `Verilator internal fault`

The test was disabled in this PR: https://github.com/antmicro/verilator/pull/100

**Comment by RRozak** [comment]
The reason is that program enters into that `if`: https://github.com/antmicro/verilator/blob/uhdm-verilator/src/UhdmAst.cpp#L128. Then it tries to parse real value by `V3Number`, but that class can't handle real values. 
It should be done in the same way as here: https://github.com/antmicro/verilator/blob/uhdm-verilator/src/UhdmAst.cpp#L166-L175
I will wait until https://github.com/alainmarcel/Surelog/issues/1167 is resolved, because it would have impact on that function.
